
d = "/h/eol/nbarron/work/precip/spol-rhi/20220610";

files = dir(d+"/*Rhi1*.nc");

cft = CfRadialToolkit();
cft.plotCfRadial(files, ...
    'VariableName', ["DBZ"], ...
    'Units', 'inches', ...
    'Position', [0,0,3,1.5], ...
    'MeteoColormapName', "Zhh", ...
    'SaveDirectory', '/h/eol/nbarron/figures/precip/spol-rhi/', ...
    'ylim', [0,12000], ...
    'xlim', [50, 150] ...
);
cft.plotCfRadial(files, ...
    'VariableName', ["ZDR_F"], ...
    'Units', 'inches', ...
    'Position', [0,0,3,1.5], ...
    'MeteoColormapName', "Zdr", ...
    'SaveDirectory', '/h/eol/nbarron/figures/precip/spol-rhi/', ...
    'ylim', [0,12000], ...
    'xlim', [50, 150] ...
);


d = "/h/eol/nbarron/work/precip/sea-pol/rhi/";

files = dir(d+"/*RHI*.nc");

cft = CfRadialToolkit();
cft.plotCfRadial(files, ...
    'VariableName', ["DBZ"], ...
    'Units', 'inches', ...
    'Position', [0,0,3,1.5], ...
    'MeteoColormapName', "Zhh", ...
    'SaveDirectory', '/h/eol/nbarron/figures/precip/spol-rhi/yonaguni-', ...
    'ylim', [0,12000], ...
    'xlim', [0, 100], ...
    'Platform', 'SEA-POL' ...
);
cft.plotCfRadial(files, ...
    'VariableName', ["ZDR"], ...
    'Units', 'inches', ...
    'Position', [0,0,3,1.5], ...
    'MeteoColormapName', "Zdr", ...
    'SaveDirectory', '/h/eol/nbarron/figures/precip/spol-rhi/yonaguni-', ...
    'ylim', [0,12000], ...
    'xlim', [0, 100], ...
    'Platform', 'SEA-POL'...
);

files = dir(d+"/*Rhi1*.nc");

cft = CfRadialToolkit();
cft.plotCfRadial(files, ...
    'VariableName', ["DBZ"], ...
    'Units', 'inches', ...
    'Position', [0,0,3,1.5], ...
    'MeteoColormapName', "Zhh", ...
    'SaveDirectory', '/h/eol/nbarron/figures/precip/spol-rhi/', ...
    'ylim', [0,12000], ...
    'xlim', [50, 150] ...
);
cft.plotCfRadial(files, ...
    'VariableName', ["ZDR_F"], ...
    'Units', 'inches', ...
    'Position', [0,0,3,1.5], ...
    'MeteoColormapName', "Zdr", ...
    'SaveDirectory', '/h/eol/nbarron/figures/precip/spol-rhi/', ...
    'ylim', [0,12000], ...
    'xlim', [50, 150] ...
);

%%% 1. process thermodynamics profile %%%
ua=readmatrix("/h/eol/nbarron/workshop/EXMIRAS/test/data/hsinchu-2022061006.csv");
p = ua(:,3); % hPa
T = ua(:,4); % C
dwp = ua(:,12); % C
RH = ua(:,5); % %
Z = ua(:,10); % m

figure
skewt(p, T, dwp)
print2

f = files(29);
d = files(29).folder;

% load geometry and variable
range = ncread(fullfile(d,f.name), 'range');
azimuth = ncread(fullfile(d,f.name), 'azimuth');
elevation = ncread(fullfile(d,f.name), 'elevation');
Zhhf = ncread(fullfile(d,f.name), 'DBZ');
Zdrf = ncread(fullfile(d,f.name), 'ZDR_F');


[rmesh, zmesh, Zhh] = cft.regridVariable(range.*cosd(elevation), azimuth, range.*sind(elevation), Zhhf);
[~, ~, Zdr] = cft.regridVariable(range, azimuth, elevation, Zdrf);

[rmeshp,zmeshp] = meshgrid([60000:1000:70000], [100:100:2000]);
Zhhp = scatteredInterpolant(double(rmesh(:)), double(zmesh(:)), double(Zhh(:)), 'linear');


figure()
for ii = 1:size(rmeshp,2)
    Zhhpi = Zhhp(rmeshp(:,ii), zmeshp(:,ii));
    plot(Zhhpi, zmeshp(:,ii)); hold on
end
print2




